language: node_js
node_js:
  - v6.10

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

script: npm run lint && npm run test

